[package]
name = "dnsclient"
version = "0.1.2"
description = "A small, simple and secure DNS client library"
authors = ["Frank Denis <github@pureftpd.org>"]
keywords = ["dns", "client"]
license = "ISC"
homepage = "https://github.com/jedisct1/rust-dnsclient"
repository = "https://github.com/jedisct1/rust-dnsclient"
categories = ["os::unix-apis"]
edition = "2018"

[dependencies]
async-std = "0.99"
dnssector = "0.1"
rand = "0.7"
